config/routes.rb
 Rails.application.routes.draw do

  root 'trips#home'
  get 'trips/select' => 'trips#select', as: :select_trip

  resources :trips do
    resources :stops do
      resources :activities
    end
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :stop
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  belongs_to :trip
  has_many :activities
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :stops
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def new
    @trip = Trip.find(params[:trip_id])
    @stop = Stop.find(params[:stop_id])
    @activity = Activity.new
    @header = "Add A New Activity"
    render "form"
  end

  def edit
    @trip = Trip.find(params[:trip_id])
    @stop = Stop.find(params[:stop_id])
    @activity = Activity.find(params[:id])
    @header = "Edit Activity"
    render "form"
  end

  def create
    stop = Stop.find(params[:stop_id])
    stop.activities.create(activity_params)
    redirect_to trip_stop_path(stop.trip_id, stop.id)
  end

  def update
    stop = Stop.find(params[:stop_id])
    activity = stop.activities.find(params[:id])
    activity.update(activity_params)
    redirect_to trip_stop_path(stop.trip_id, stop.id)
  end

  def destroy
    stop = Stop.find(params[:stop_id])
    Activity.find(params[:id]).destroy
    redirect_to trip_stop_path(stop.trip_id, stop.id)
  end

  private

  def activity_params
    params.require(:activity).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :find_trip, only: [:new, :edit]

  def show
    id = params[:id]
    @stop = Stop.find(id)
    @activities = @stop.activities
  end

  def new
    @stop = Stop.new
    @header = "Add A New Destination"
    render "form"
  end

  def edit
    @stop = Stop.find(params[:id])
    @header = "Edit Destination"
    render "form"
  end

  def create
    trip = Trip.find(params[:trip_id])
    trip.stops.create(stop_params)
    redirect_to trip_path(params[:trip_id])
  end

  def update
    trip = Trip.find(params[:trip_id])
    stop = trip.stops.find(params[:id])
    stop.update(stop_params)
    redirect_to trip_path(params[:trip_id])
  end

  def destroy
    trip_id = params[:trip_id]
    Stop.find(params[:id]).destroy
    redirect_to trip_path(trip_id)
  end

  private

  def find_trip
    @trip = Trip.find(params[:trip_id])
  end

  def stop_params
    params.require(:stop).permit(:name, :description)
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def home
    @not_home = false
  end

  def index
    @trips = Trip.all
  end

  def show
    id = params[:id]
    @trip = Trip.find(id)
    @stops = @trip.stops
  end

  def new
    @trip = Trip.new
    @header = "Create A New Trip"
    render "form"
  end

  def edit
    @trip = Trip.find(params[:id])
    @header = "Edit Trip"
    render "form"
  end

  def create
    Trip.create(trip_params)
    redirect_to trips_path
  end

  def update
    Trip.update(params[:id], trip_params)
    redirect_to trip_path(params[:id])
  end

  def destroy
    id = params[:id]
    Trip.find(id).destroy
    redirect_to trips_path
  end

  def select
    redirect_to trip_path(params[:trip][:id])
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :description)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/activities/form.html.erb
<h1><%= @header %></h1>
<%= form_for [@trip, @stop, @activity] do |f| %>
    <table>
      <tbody>
        <tr>
          <td><%= f.label :name, "Name:" %></td>
          <td><%= f.text_field :name %></td>
        </tr>
      </tbody>
    </table>
    <%= f.submit %>
<% end %>

app/views/activities/new.html.erb
<h1><%= @header %></h1>
<%= form_for [@trip, @stop, @activity] do |f| %>
    <table>
      <tbody>
        <tr>
          <td><%= f.label :name, "Name:" %></td>
          <td><%= f.text_field :name %></td>
        </tr>
      </tbody>
    </table>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Alegreya+Sans' rel='stylesheet' type='text/css'>
  <title>Road Trip Planner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav>
      <% if @not_home != false %>
        <%= link_to '<i class="fa fa-home"></i>'.html_safe, root_path %>
      <% else %>
        <br><br>
      <% end %>
    </nav>
  </header>
  <section>
    <%= yield %>
  </section>

  <footer>
    <span>© 2015 Desiree Poland</span>
  </footer>

</body>
</html>

app/views/stops/form.html.erb
<h1><%= @header %></h1>
<%= form_for [@trip, @stop] do |f| %>
    <table>
      <tbody>
        <tr>
          <td><%= f.label :name, "Name:" %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label "Description:" %></td>
          <td><%= f.text_field :description %></td>
        </tr>
      </tbody>
    </table>
    <%= f.submit %>
<% end %>

app/views/stops/new.html.erb
<h1><%= @header %></h1>
<%= form_for [@trip, @stop] do |f| %>
    <table>
      <tbody>
        <tr>
          <td><%= f.label :name, "Name:" %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label "Description:" %></td>
          <td><%= f.text_field :description %></td>
        </tr>
      </tbody>
    </table>
    <%= f.submit %>
<% end %>

<!-- , url: { action: @action }, method: @method do |f| -->

app/views/stops/show.html.erb
<h1><%= @stop.name %></h1>

<% if !@stop.description.empty? %>
  <p>Description: <%= @stop.description %></p>
<% end %>
<p>Trip: <%= link_to @stop.trip.name,  trip_path(@stop.trip_id)%></p>

<h3>Activities:</h3>
<table>
  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= link_to "✏︎", edit_trip_stop_activity_path(@stop.trip_id, @stop.id, activity.id) %></td>
        <td><%=link_to "☒", trip_stop_activity_path(@stop.trip_id, @stop.id, activity.id), method: :delete, data: {confirm: "Confirm Deletion"} %></td>
      </tr>
    <% end %>
    <% if @activities.count == 0 %>
      <tr>
        <td>There are currently no activities for this destination.</td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "+ Add An Activity", new_trip_stop_activity_path(@stop.trip_id, @stop.id) %>

app/views/trips/form.html.erb
<h1><%= @header %></h1>
<%= form_for @trip do |f| %>
    <table>
      <tbody>
        <tr>
          <td><%= f.label :name, "Name:" %></td>
          <td><%= f.text_area(:name, size: "25x1") %></td>
        </tr>
        <tr>
          <td><%= f.label "Description:" %></td>
          <td><%= f.text_area(:description, size: "25x3") %></td>
        </tr>
      </tbody>
    </table>
    <%= f.submit %>
<% end %>

app/views/trips/home.html.erb
<h1 class="hometitle">Go Somewhere</h1>

<h3>View A Trip</h3>
<%= form_tag select_trip_path, method: :get do %>
      <%= collection_select(:trip, :id, Trip.all, :id, :name, prompt: "Select One:") %>
      <br>
      <%= submit_tag "View Trip" %>
  <% end %>
<br><br>

<%= link_to " | Create A Trip | ", new_trip_path %>
<%= link_to " | View All Trips | ", trips_path %>

app/views/trips/index.html.erb
<h1>All Trips</h1>
<table>
  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= link_to trip.name, trip_path(trip.id) %></td>
        <td><%=link_to "☒", trip_path(trip.id), method: :delete, data: {confirm: "Confirm Deletion"} %></td>
      </tr>
    <% end %>
    <% if @trips.count == 0 %>
      <tr>
        <td>There are currently no planned trips.</td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "+ Create A Trip", new_trip_path %>

app/views/trips/new.html.erb
<h1><%= @header %></h1>
<%= form_for @trip do |f| %>
    <table>
      <tbody>
        <tr>
          <td><%= f.label :name, "Name:" %></td>
          <td><%= f.text_area(:name, size: "25x1") %></td>
        </tr>
        <tr>
          <td><%= f.label "Description:" %></td>
          <td><%= f.text_area(:description, size: "25x3") %></td>
        </tr>
      </tbody>
    </table>
    <%= f.submit %>
<% end %>

app/views/trips/show.html.erb
<h1><%= @trip.name %></h1>

<%= link_to "✐", edit_trip_path(@trip.id) %>
<%=link_to "☒", trip_path(@trip.id), method: :delete, data: {confirm: "Confirm Deletion"} %>

<% if !@trip.description.empty? %>
  <p>Description: <%= @trip.description %></p>
<% end %>

<h3>Destinations:</h3>
<table>
  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= link_to stop.name, trip_stop_path(@trip.id, stop.id) %></td>
        <td><%= link_to "✏︎", edit_trip_stop_path(@trip.id, stop.id) %></td>
        <td><%=link_to "☒", trip_stop_path(@trip.id, stop.id), method: :delete, data: {confirm: "Confirm Deletion"} %></td>
      </tr>
    <% end %>
    <% if @stops.count == 0 %>
      <tr>
        <td>There are currently no destinations.</td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "+ Add A Destination", new_trip_stop_path(@trip.id) %>